services:  
  dobbe:
    image: node:20
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    command: "npm start"
    volumes:
      - ./:/home/node/app
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
